"""
Main persona fabricator that orchestrates the entire process.
"""

import random
from datetime import datetime
from pathlib import Path
from typing import Optional

from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich.table import Table

from .config import PersonaConfig, FabricateSettings, COMPLEXITY_PROFILES
from .generator import CodeGenerator, GeneratedRepo
from .git_ops import GitOperations, generate_commit_dates
from .github_client import GitHubClient

console = Console()


class PersonaFabricator:
    """
    Orchestrates the fabrication of a complete GitHub persona.
    
    Creates multiple repositories with realistic commit histories,
    all generated by AI to simulate authentic developer activity.
    """
    
    def __init__(
        self,
        gemini_api_key: str,
        github_token: str,
        github_username: Optional[str] = None,
        work_dir: str = "./fabricated_repos",
        author_name: Optional[str] = None,
        author_email: Optional[str] = None
    ):
        self.generator = CodeGenerator(gemini_api_key)
        self.github = GitHubClient(github_token, github_username)
        
        # Get user info for author details
        user_info = self.github.get_user_info()
        self.author_name = author_name or user_info.get("name") or user_info["login"]
        self.author_email = author_email or user_info.get("email") or f"{user_info['login']}@users.noreply.github.com"
        
        self.git_ops = GitOperations(work_dir, self.author_name, self.author_email)
        self.work_dir = Path(work_dir)
        
        console.print(Panel(
            f"[bold]Fabricate[/bold] - GitHub Persona Generator\n\n"
            f"User: [cyan]{user_info['login']}[/cyan]\n"
            f"Author: [cyan]{self.author_name} <{self.author_email}>[/cyan]",
            title="Initialized",
            border_style="green"
        ))
    
    def _select_complexity(self) -> str:
        """Select a complexity level with weighted randomness."""
        # Favor medium complexity, but include variety
        weights = {
            "low": 0.3,
            "medium": 0.5,
            "high": 0.2
        }
        return random.choices(
            list(weights.keys()),
            weights=list(weights.values())
        )[0]
    
    def _select_language(self, languages: list[str], repo_index: int) -> str:
        """Select a language, ensuring variety across repos."""
        # Cycle through languages but add some randomness
        base_index = repo_index % len(languages)
        if random.random() < 0.3:  # 30% chance to pick random instead
            return random.choice(languages)
        return languages[base_index]
    
    def fabricate_repo(
        self,
        config: PersonaConfig,
        repo_index: int,
        total_repos: int,
        existing_names: list[str],
        push_to_github: bool = True
    ) -> Optional[GeneratedRepo]:
        """Fabricate a single repository."""
        
        language = self._select_language(config.languages, repo_index)
        complexity = self._select_complexity()
        num_commits = config.generate_commit_count()
        
        console.print(f"\n[bold]═══ Repository {repo_index + 1}/{total_repos} ═══[/bold]")
        console.print(f"Language: [cyan]{language}[/cyan] | Complexity: [yellow]{complexity}[/yellow] | Commits: [green]{num_commits}[/green]")
        
        try:
            # Generate the repository content
            generated_repo = self.generator.generate_full_repo(
                language=language,
                complexity=complexity,
                num_commits=num_commits,
                name_style=config.repo_name_style,
                existing_names=existing_names,
                technologies=config.technologies,
                categories=config.categories
            )
            
            # Generate commit dates
            commit_dates = generate_commit_dates(
                num_commits=len(generated_repo.commits),
                history_days=config.history_days,
                repo_index=repo_index,
                total_repos=total_repos
            )
            
            # Create local repository with commits
            local_repo = self.git_ops.apply_generated_repo(
                generated_repo,
                commit_dates,
                author_name=self.author_name,
                author_email=self.author_email
            )
            
            if push_to_github:
                # Create remote repository
                remote_url = self.github.create_remote_repo(
                    name=generated_repo.name,
                    description=generated_repo.description,
                    private=False,
                    topics=generated_repo.topics
                )
                
                # Push to GitHub
                self.github.push_repo(local_repo, remote_url)
            
            return generated_repo
            
        except Exception as e:
            console.print(f"[red]Error creating repository: {e}[/red]")
            import traceback
            traceback.print_exc()
            return None
    
    def fabricate_persona(
        self,
        config: PersonaConfig,
        push_to_github: bool = True,
        cleanup_local: bool = False
    ) -> list[GeneratedRepo]:
        """
        Fabricate a complete GitHub persona with multiple repositories.
        
        Args:
            config: Configuration for the persona
            push_to_github: Whether to push repos to GitHub
            cleanup_local: Whether to remove local repos after pushing
            
        Returns:
            List of successfully generated repositories
        """
        
        console.print(Panel(
            f"[bold]Fabrication Configuration[/bold]\n\n"
            f"Repositories: [cyan]{config.num_repos}[/cyan]\n"
            f"Languages: [cyan]{', '.join(config.languages)}[/cyan]\n"
            f"History: [cyan]{config.history_days}[/cyan] days\n"
            f"Commits per repo: [cyan]{config.min_commits_per_repo}-{config.max_commits_per_repo}[/cyan]",
            title="Starting Fabrication",
            border_style="blue"
        ))
        
        generated_repos = []
        existing_names = self.github.list_repos() if push_to_github else []
        
        for i in range(config.num_repos):
            repo = self.fabricate_repo(
                config=config,
                repo_index=i,
                total_repos=config.num_repos,
                existing_names=existing_names + [r.name for r in generated_repos],
                push_to_github=push_to_github
            )
            
            if repo:
                generated_repos.append(repo)
                
                if cleanup_local:
                    self.git_ops.cleanup_repo(repo.name)
        
        # Print summary
        self._print_summary(generated_repos, config)
        
        return generated_repos
    
    def _print_summary(self, repos: list[GeneratedRepo], config: PersonaConfig) -> None:
        """Print a summary of the fabrication."""
        
        table = Table(title="\nFabrication Summary")
        table.add_column("Repository", style="cyan")
        table.add_column("Language", style="yellow")
        table.add_column("Commits", style="green")
        table.add_column("Description")
        
        total_commits = 0
        for repo in repos:
            table.add_row(
                repo.name,
                repo.language,
                str(len(repo.commits)),
                repo.description[:50] + "..." if len(repo.description) > 50 else repo.description
            )
            total_commits += len(repo.commits)
        
        console.print(table)
        
        console.print(Panel(
            f"[bold green]Fabrication Complete![/bold green]\n\n"
            f"Repositories created: [cyan]{len(repos)}/{config.num_repos}[/cyan]\n"
            f"Total commits: [cyan]{total_commits}[/cyan]\n"
            f"Languages used: [cyan]{len(set(r.language for r in repos))}[/cyan]",
            border_style="green"
        ))


def run_fabrication(
    gemini_api_key: str,
    github_token: str,
    languages: list[str],
    num_repos: int,
    history_days: int,
    min_commits: int = 5,
    max_commits: int = 37,
    github_username: Optional[str] = None,
    work_dir: str = "./fabricated_repos",
    push_to_github: bool = True,
    cleanup_local: bool = False,
    technologies: Optional[list[str]] = None,
    categories: Optional[list[str]] = None
) -> list[GeneratedRepo]:
    """
    Convenience function to run a complete fabrication.
    
    Args:
        gemini_api_key: Google Gemini API key for code generation
        github_token: GitHub personal access token
        languages: List of programming languages to use
        num_repos: Number of repositories to create
        history_days: How far back the commit history should go
        min_commits: Minimum commits per repository
        max_commits: Maximum commits per repository
        github_username: GitHub username (auto-detected if not set)
        work_dir: Directory for temporary repository files
        push_to_github: Whether to push to GitHub
        cleanup_local: Whether to remove local files after pushing
        technologies: Optional list of technologies to use (e.g., tailwind, prisma)
        categories: Optional list of project categories (e.g., cli_tool, web_app)
        
    Returns:
        List of generated repositories
    """
    
    config = PersonaConfig(
        languages=languages,
        num_repos=num_repos,
        history_days=history_days,
        min_commits_per_repo=min_commits,
        max_commits_per_repo=max_commits,
        technologies=technologies,
        categories=categories
    )
    
    fabricator = PersonaFabricator(
        gemini_api_key=gemini_api_key,
        github_token=github_token,
        github_username=github_username,
        work_dir=work_dir
    )
    
    return fabricator.fabricate_persona(
        config=config,
        push_to_github=push_to_github,
        cleanup_local=cleanup_local
    )
